version: "3.9"

services:
  mulila_governor:
    container_name: mulila_governor
    build: .
    restart: unless-stopped

    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mulila_governor.rule=Host(`mulila.pasbestventures.com`)"
      - "traefik.http.routers.mulila_governor.entrypoints=websecure"
      - "traefik.http.routers.mulila_governor.tls.certresolver=letsencrypt"
      - "traefik.http.services.mulila_governor.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true
